// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqEZn1vaHmYbGF6bQRM0qICIKqN-w5bI',
    appId: '1:1034440254821:android:cd9fe0ce45e56c44d0ad8c',
    messagingSenderId: '1034440254821',
    projectId: 'cubeassesment-cdc59',
    databaseURL: 'https://cubeassesment-cdc59-default-rtdb.firebaseio.com',
    storageBucket: 'cubeassesment-cdc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqaJXrXlVrvq51rsx7A6osSxQOMpu6dM',
    appId: '1:1034440254821:ios:813826e14924bea9d0ad8c',
    messagingSenderId: '1034440254821',
    projectId: 'cubeassesment-cdc59',
    databaseURL: 'https://cubeassesment-cdc59-default-rtdb.firebaseio.com',
    storageBucket: 'cubeassesment-cdc59.appspot.com',
    iosBundleId: 'com.example.cubeassesment',
  );
}
